import { App, Notice, TFile, normalizePath } from 'obsidian';
import { AIClient } from '../ai/client';
import { VaultIndexer } from '../graph/vault-index';
import { SynthesisTemplate } from './templates';

export interface RunnerOptions {
  outputFolder: string; // e.g. "Synthesis"
}

export async function runSynthesis(
  app: App,
  ai: AIClient,
  indexer: VaultIndexer,
  template: SynthesisTemplate,
  arg: string | undefined,
  mode: number,
  opts: RunnerOptions
): Promise<TFile | null> {
  if (!ai.isReady()) {
    new Notice('Configure your Anthropic API key in plugin settings first.');
    return null;
  }
  const slice = template.buildSlice(indexer.get(), arg);
  if (!slice) {
    new Notice('Not enough tagged content for this template yet.');
    return null;
  }
  new Notice(`Synthesizing with ${template.name}…`);
  const instruction = template.buildInstruction(arg);
  let result;
  try {
    result = await ai.synthesize(template.name, instruction, slice.body, mode);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    new Notice('Synthesis failed: ' + msg);
    return null;
  }

  const date = new Date().toISOString().slice(0, 10);
  const stem = `${date} — ${template.id}${arg ? ' — ' + safe(arg) : ''}`;
  const folder = normalizePath(opts.outputFolder);
  await ensureFolder(app, folder);
  const path = normalizePath(`${folder}/${stem}.md`);
  const body = renderOutput(template, arg, result.text, slice.body, result);
  let file = app.vault.getAbstractFileByPath(path);
  if (file instanceof TFile) {
    await app.vault.modify(file, body);
  } else {
    file = await app.vault.create(path, body);
  }
  new Notice(`Synthesis written to ${path}`);
  return file as TFile;
}

function renderOutput(
  template: SynthesisTemplate,
  arg: string | undefined,
  body: string,
  slice: string,
  meta: { inputTokens: number; outputTokens: number; cacheHit: boolean }
): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('sr_synthesis: true');
  lines.push(`sr_template: ${template.id}`);
  if (arg) lines.push(`sr_arg: ${arg}`);
  lines.push(`sr_created: ${new Date().toISOString()}`);
  lines.push('---');
  lines.push('');
  lines.push(`# ${template.name}${arg ? ' — ' + arg : ''}`);
  lines.push('');
  lines.push('> [!info] Generated by Semantic Reading. ' +
    `Tokens: ${meta.inputTokens} in / ${meta.outputTokens} out${meta.cacheHit ? ' (cache hit)' : ''}.`);
  lines.push('');
  lines.push(body.trim());
  lines.push('');
  lines.push('---');
  lines.push('## Source slice');
  lines.push('');
  lines.push('<details><summary>Show what was sent to the model</summary>');
  lines.push('');
  lines.push(slice);
  lines.push('');
  lines.push('</details>');
  return lines.join('\n');
}

async function ensureFolder(app: App, folder: string): Promise<void> {
  if (!folder) return;
  const existing = app.vault.getAbstractFileByPath(folder);
  if (existing) return;
  try { await app.vault.createFolder(folder); } catch { /* race-safe */ }
}

function safe(s: string): string {
  return s.replace(/[^A-Za-z0-9 _-]/g, '').slice(0, 60);
}
