// Sidecar markdown file per PDF — the storage layer for PDF tags.
//
// Each tagged span in a PDF becomes one paragraph in `<basename>.sr.md` colocated
// with the PDF. The paragraph is written as plain markdown that the existing
// `parseParagraph()` already understands, so the vault indexer picks it up with
// no extra wiring:
//
//   {{Tag|[[name.pdf#page=4|selected text]]}} ^pdf-p4-a91c2f01
//
// - The wikilink target's `#page=N` anchor makes Obsidian jump to the page on click.
// - The display text is what shows in the indexer's `mention.text`.
// - The mention picks up `wikilink = "name.pdf#page=4"` for free, which hub-pages
//   uses to render a one-click backlink straight to the PDF.
// - The trailing `^pdf-pN-hash8` is the idempotency key: re-tagging the same span
//   skips the append.

import { App, TFile, normalizePath } from 'obsidian';
import { formatRectForWikilink } from './rect-drag';

// Two shapes share one entry type: text-anchored (selection has real text) and
// rect-anchored (image PDFs, or drag-over-margin where no text was selected).
// Both still land as a single `{{Tag|[[...]]}}` line so the parser, indexer,
// hubs, cards, MCP and exports stay agnostic.
export interface SidecarTextEntry {
  kind: 'text';
  pdfPath: string;
  page: number;
  text: string;
  tag: string;
  blockId: string;
}

export interface SidecarRectEntry {
  kind: 'rect';
  pdfPath: string;
  page: number;
  rect: { leftPct: number; topPct: number; widthPct: number; heightPct: number };
  tag: string;
  blockId: string;
}

export type SidecarEntry = SidecarTextEntry | SidecarRectEntry;

// Where the sidecar lives for a given PDF path. Colocated, distinct from any
// PDF++ conventions, plugin-prefixed so we don't collide.
export function sidecarPathFor(pdfPath: string): string {
  return normalizePath(pdfPath.replace(/\.pdf$/i, '') + '.sr.md');
}

export function isSidecarPath(path: string): boolean {
  return /\.sr\.md$/i.test(path);
}

// Append `entry` to its PDF's sidecar, creating the file if absent. No-op if
// an entry with the same blockId is already present.
export async function appendEntry(app: App, entry: SidecarEntry): Promise<'created' | 'appended' | 'skipped'> {
  const sidecarPath = sidecarPathFor(entry.pdfPath);
  const existing = app.vault.getAbstractFileByPath(sidecarPath);
  const line = formatEntry(entry);

  if (existing instanceof TFile) {
    const current = await app.vault.read(existing);
    if (current.includes('^' + entry.blockId)) return 'skipped';
    const separator = current.endsWith('\n\n') ? '' : (current.endsWith('\n') ? '\n' : '\n\n');
    await app.vault.modify(existing, current + separator + line + '\n');
    return 'appended';
  }

  const header = sidecarHeader(entry.pdfPath);
  await app.vault.create(sidecarPath, header + line + '\n');
  return 'created';
}

function sidecarHeader(pdfPath: string): string {
  const basename = pdfPath.slice(pdfPath.lastIndexOf('/') + 1);
  // Trailing '' twice → header ends with `\n\n`, so the first entry sits in
  // its own paragraph rather than fusing with the `> [!note]` callout.
  return [
    '---',
    'sr_pdf_sidecar: true',
    `sr_pdf: "${pdfPath}"`,
    '---',
    '',
    `# Semantic reading annotations — ${basename}`,
    '',
    '> [!note] Auto-generated by the semantic-reading plugin. Each entry below is a tagged selection from the PDF; click the page link to jump back to the source.',
    '',
    '',
  ].join('\n');
}

// Compose the single-paragraph entry. Kept exported so tests / future migrations
// can re-derive the canonical shape.
export function formatEntry(entry: SidecarEntry): string {
  const pdfBasename = entry.pdfPath.slice(entry.pdfPath.lastIndexOf('/') + 1);
  if (entry.kind === 'rect') {
    const rectStr = formatRectForWikilink(entry.rect);
    const target = `${pdfBasename}#page=${entry.page}&rect=${rectStr}`;
    const display = `Page ${entry.page} region`;
    return `{{${entry.tag}|[[${target}|${display}]]}} ^${entry.blockId}`;
  }
  const display = sanitizeDisplay(entry.text);
  const target = `${pdfBasename}#page=${entry.page}`;
  return `{{${entry.tag}|[[${target}|${display}]]}} ^${entry.blockId}`;
}

// Display text rules for the wikilink:
// - Can't contain `]]` (would close the wikilink early); replace with `] ]`.
// - Can't contain raw newlines (would break the paragraph).
// - Trim outer whitespace, cap length to avoid runaway sidecar lines.
function sanitizeDisplay(text: string): string {
  const flat = text.replace(/\s+/g, ' ').trim().replace(/\]\]/g, '] ]');
  const MAX = 500;
  return flat.length > MAX ? flat.slice(0, MAX - 1) + '…' : flat;
}
